import asyncio
from collections import defaultdict
from datetime import datetime, timezone, timedelta

from .dispatcher import dispatch_event
from .models import SessionLocal, Bed, Embarcado, ReceivedEvent
from .config import WARNING_DELAY_MINUTES 
from .presence import check_presence
from .mqtt_client import publish_available_beds

# --- Configurações ---
RETRY_PRESENCE_FREQUENCY_SEC = 30
AGGREGATOR_LOOP_INTERVAL_SEC = 2

# --- Estruturas de Dados em Memória ---
_buffer = []
_pending_mac_checks = {}

def enqueue_event(evt: dict):
    """ Coloca um novo evento no buffer para ser processado. """
    _buffer.append(evt)
    print(f"[aggregator] Evento enfileirado: {evt}")

# --- NOVA FUNÇÃO HELPER ---
def _update_event_status(event_id: int, status: str, detail: str):
    """ Pequena função para atualizar o status de um evento no banco de dados. """
    db = SessionLocal()
    try:
        event_to_update = db.query(ReceivedEvent).filter(ReceivedEvent.id == event_id).first()
        if event_to_update:
            event_to_update.status = status
            event_to_update.status_detail = detail
            db.commit()
    except Exception as e:
        print(f"[aggregator-update] ERRO ao atualizar evento {event_id}: {e}")
        db.rollback()
    finally:
        db.close()

# --- LÓGICA DE RETRY ATUALIZADA ---
async def _retry_presence_task(wifi_mac: str, beacon_mac: str, original_event_id: int, esp_id: str):
    """
    Tarefa em segundo plano que verifica a presença.
    LÓGICA ATUALIZADA: Se a ausência persistir, CRIA UM NOVO EVENTO DE WARNING no banco
    e o despacha para o sistema externo.
    """
    print(f"[aggregator-retry] Iniciada tarefa para Beacon '{beacon_mac}' (MAC Wi-Fi: {wifi_mac}).")
    
    start_time = datetime.now(timezone.utc)
    warning_created = False # Controle para garantir que o warning seja criado apenas uma vez
    
    while True:
        await asyncio.sleep(RETRY_PRESENCE_FREQUENCY_SEC)
        
        loop = asyncio.get_running_loop()
        is_present = await loop.run_in_executor(None, check_presence, wifi_mac)

        if is_present:
            # A lógica de sucesso quando o Wi-Fi é encontrado permanece a mesma
            print(f"[aggregator-retry] SUCESSO! MAC Wi-Fi '{wifi_mac}' encontrado na rede.")
            db = SessionLocal()
            try:
                bed = db.query(Bed).filter(Bed.mac_beacon == beacon_mac).first()
                emb = db.query(Embarcado).filter(Embarcado.id_esp == esp_id).first()

                if emb and bed and bed.quarto is None:
                    bed.quarto = emb.quarto
                    db.commit()
                    publish_available_beds()
                    print("Entrei aqui")

                    dispatch_payload = {
                        "quarto": bed.quarto, "cama": bed.nome_cama, "status": "GET",
                        "dataOn": bed.data,
                    }
                    await loop.run_in_executor(None, dispatch_event, dispatch_payload)

                    _update_event_status(
                        original_event_id, 
                        status="Resolvido", 
                        detail=f"Cama '{bed.nome_cama}' associada ao quarto '{emb.quarto}' via nova tentativa."
                    )
                break 
            finally:
                db.close()
        
        elif not warning_created:
            elapsed_time = datetime.now(timezone.utc) - start_time
            if elapsed_time > timedelta(minutes=WARNING_DELAY_MINUTES):
                print(f"[aggregator-retry] MAC '{wifi_mac}' ausente por mais de {WARNING_DELAY_MINUTES} min. GERANDO WARNING.")
                db = SessionLocal()
                try:
                    bed = db.query(Bed).filter(Bed.mac_beacon == beacon_mac).first()
                    emb = db.query(Embarcado).filter(Embarcado.id_esp == esp_id).first()
                    
                    if bed and emb:
                        # --- Bloco para Criar e Salvar o Evento WARNING ---
                        timestamp_agora = datetime.now(timezone.utc)
                        
                        # 1. Cria o novo evento de WARNING no banco
                        warning_event = ReceivedEvent(
                            esp_id=esp_id, cama=beacon_mac,
                            action="WARNING", status="OK",
                            status_detail=f"Alerta gerado para cama '{bed.nome_cama}' com MAC ausente por mais de {WARNING_DELAY_MINUTES} min.",
                            data_on=emb.data,
                            raw={"reason": "Auto-generated by aggregator", "original_event_id": original_event_id}
                        )
                        db.add(warning_event)
                        db.commit()

                        # 2. Despacha o WARNING para o Connecta
                        warning_payload = {
                            "quarto": emb.quarto, "cama": bed.nome_cama, 
                            "status": "WARNING", "dataOn": timestamp_agora.isoformat()
                        }
                        await loop.run_in_executor(None, dispatch_event, warning_payload)
                        
                        warning_created = True # Marca que o alerta foi criado para não repetir
                finally:
                    db.close()

    # Limpeza final da tarefa
    if wifi_mac in _pending_mac_checks:
        del _pending_mac_checks[wifi_mac]
    print(f"[aggregator-retry] Finalizada tarefa de verificação para MAC Wi-Fi '{wifi_mac}'.")

# --- LÓGICA DE PROCESSAMENTO PRINCIPAL TOTALMENTE REFEITA ---
async def _process_events_batch(events: list):
    """
    Processa um lote de eventos para um mesmo beacon.
    A lógica de WARNING foi movida para a tarefa de retry.
    """
    loop = asyncio.get_running_loop()
    db = SessionLocal()
    
    try:
        # --- Lógica de 'OUT' (sem alterações) ---
        out_events = [e for e in events if e.get("status") == "OUT"]
        if out_events:
            main_out_event = out_events[0]
            event_id = main_out_event.get("event_id")
            beacon_mac = main_out_event.get("cama")
            print(f"[aggregator] Evento 'OUT' detectado para o beacon '{beacon_mac}'.")
            
            for evt in out_events[1:]:
                _update_event_status(evt.get("event_id"), "Ignorado", "Evento OUT duplicado no mesmo lote.")

            bed = db.query(Bed).filter(Bed.mac_beacon == beacon_mac).first()
            if bed:
                if bed.mac_address in _pending_mac_checks:
                    _pending_mac_checks[bed.mac_address].cancel()
                    del _pending_mac_checks[bed.mac_address]
                
                if bed.quarto is not None:
                    print(f"[aggregator] Desassociando cama '{bed.nome_cama}' do quarto '{bed.quarto}'.")
                    bed.quarto = None
                    db.commit()
                    publish_available_beds()
                    _update_event_status(event_id, "OK", f"Cama '{bed.nome_cama}' desassociada com sucesso.")
                else:
                    _update_event_status(event_id, "Confirmado", "Cama já estava desassociada. Nenhuma ação necessária.")
            else:
                _update_event_status(event_id, "Erro", f"Cama com beacon '{beacon_mac}' não cadastrada.")
            return

        # --- Lógica de 'GET' ---
        get_events = [e for e in events if e.get("status") == "GET"]
        if not get_events:
            return

        best_event = max(get_events, key=lambda e: e.get("RSSI", -1000))
        event_id = best_event.get("event_id")
        beacon_mac = best_event.get("cama")

        for evt in get_events:
            if evt is not best_event:
                _update_event_status(evt.get("event_id"), "Ignorado", f"Sinal mais fraco (RSSI: {evt.get('RSSI', 'N/A')}) ou duplicado.")
        
        bed = db.query(Bed).filter(Bed.mac_beacon == beacon_mac).first()
        emb = db.query(Embarcado).filter(Embarcado.id_esp == best_event['esp_id']).first()

        if not bed or not emb:
            detail = f"Cama (beacon: {beacon_mac})" if not bed else f"ESP ({best_event['esp_id']})"
            _update_event_status(event_id, "Erro", f"Componente não cadastrado: {detail}.")
            return

        if bed.quarto == emb.quarto:
            _update_event_status(event_id, "Confirmado", f"Cama '{bed.nome_cama}' já estava no quarto '{emb.quarto}'.")
            return
        
        is_present = await loop.run_in_executor(None, check_presence, bed.mac_address)
        bed.quarto = emb.quarto
        db.commit()
        
        if is_present:
            
            publish_available_beds()
            
            dispatch_payload = {"quarto": bed.quarto, "cama": bed.nome_cama, "status": "GET", "dataOn": datetime.now(timezone.utc).isoformat(), "wifi": best_event.get("wifi")}
            await loop.run_in_executor(None, dispatch_event, dispatch_payload)
            
            _update_event_status(event_id, "OK", f"Cama '{bed.nome_cama}' associada ao quarto '{emb.quarto}'.")
        else:
            # --- Bloco Modificado ---
            # MAC não encontrado: Apenas marca como Pendente e inicia a tarefa de retry.
            # A lógica de WARNING foi movida para dentro da _retry_presence_task.
            _update_event_status(event_id, "Pendente", "MAC da cama não encontrado. Nova verificação agendada.")
            
            if bed.mac_address not in _pending_mac_checks:
                task = asyncio.create_task(
                    _retry_presence_task(
                        wifi_mac=bed.mac_address, 
                        beacon_mac=beacon_mac, 
                        original_event_id=event_id,
                        esp_id=best_event['esp_id'] # Passando o esp_id para o contexto do warning
                    )
                )
                _pending_mac_checks[bed.mac_address] = task
    finally:
        db.close()

def cancel_pending_task(wifi_mac: str) -> bool:
    """
    Busca e cancela uma tarefa de retry pendente com base no MAC Wi-Fi da cama.

    Retorna True se a tarefa foi encontrada e cancelada, False caso contrário.
    """
    if wifi_mac in _pending_mac_checks:
        task = _pending_mac_checks[wifi_mac]
        task.cancel()
        # Remove a tarefa do dicionário para evitar chamadas futuras
        del _pending_mac_checks[wifi_mac]
        print(f"[aggregator-cancel] Tarefa para o MAC {wifi_mac} foi cancelada externamente.")
        return True
    
    print(f"[aggregator-cancel] Nenhuma tarefa pendente encontrada para o MAC {wifi_mac}.")
    return False

async def main_aggregator_loop():
    """ O loop principal que orquestra as tarefas. """
    print(f"[aggregator] Agregador com lógica de status iniciada. Loop a cada {AGGREGATOR_LOOP_INTERVAL_SEC}s.")
    
    while True:
        await asyncio.sleep(AGGREGATOR_LOOP_INTERVAL_SEC)
        
        if not _buffer:
            continue

        events_to_process = list(_buffer)
        _buffer.clear()

        events_by_beacon = defaultdict(list)
        for evt in events_to_process:
            # Ignora eventos sem o campo 'cama'
            if "cama" in evt:
                events_by_beacon[evt["cama"]].append(evt)
        
        print(f"\n[aggregator] Processando {len(events_to_process)} eventos para {len(events_by_beacon)} beacons...")
        for beacon_mac, events in events_by_beacon.items():
            await _process_events_batch(events)