"""Adiciona status_rede a tabela Embarcado

Revision ID: 96596ddc8e2d
Revises: b96fa46fa444
Create Date: 2025-07-31 17:37:26.431332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96596ddc8e2d'
down_revision: Union[str, Sequence[str], None] = 'b96fa46fa444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarcados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_rede', sa.String(length=20),
                                      nullable=False,
                                      server_default='online'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarcados', schema=None) as batch_op:
        batch_op.drop_column('status_rede')

    # ### end Alembic commands ###