"""add colunas X

Revision ID: 9e3ba1e0494a
Revises: d1b6053ed49e
Create Date: 2025-12-15 10:25:19.453589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3ba1e0494a'
down_revision: Union[str, Sequence[str], None] = 'd1b6053ed49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_assets_mac_address'))
        batch_op.create_unique_constraint('uq_assets_mac_address', ['mac_address'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assets_mac_address', type_='unique')
        batch_op.create_index(batch_op.f('ix_assets_mac_address'), ['mac_address'], unique=1)
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
