"""Criação das tabelas iniciais

Revision ID: a82eaf94a2f0
Revises: 
Create Date: 2025-07-30 15:34:29.241811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82eaf94a2f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_global_settings_key'), 'global_settings', ['key'], unique=False)
    op.create_table('quartos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_quartos_id'), 'quartos', ['id'], unique=False)
    op.create_table('received_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esp_id', sa.String(), nullable=False),
    sa.Column('ativo', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_detail', sa.String(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('wifi', sa.Integer(), nullable=True),
    sa.Column('data_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_received_events_action'), 'received_events', ['action'], unique=False)
    op.create_index(op.f('ix_received_events_ativo'), 'received_events', ['ativo'], unique=False)
    op.create_index(op.f('ix_received_events_data_on'), 'received_events', ['data_on'], unique=False)
    op.create_index(op.f('ix_received_events_esp_id'), 'received_events', ['esp_id'], unique=False)
    op.create_index(op.f('ix_received_events_id'), 'received_events', ['id'], unique=False)
    op.create_index(op.f('ix_received_events_status'), 'received_events', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_ativo', sa.String(), nullable=False),
    sa.Column('mac_beacon', sa.String(), nullable=False),
    sa.Column('quarto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_ativo')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_mac_beacon'), 'assets', ['mac_beacon'], unique=True)
    op.create_table('embarcados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_esp', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quarto_id', sa.Integer(), nullable=False),
    sa.Column('rssi_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embarcados_id'), 'embarcados', ['id'], unique=False)
    op.create_index(op.f('ix_embarcados_id_esp'), 'embarcados', ['id_esp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embarcados_id_esp'), table_name='embarcados')
    op.drop_index(op.f('ix_embarcados_id'), table_name='embarcados')
    op.drop_table('embarcados')
    op.drop_index(op.f('ix_assets_mac_beacon'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_received_events_status'), table_name='received_events')
    op.drop_index(op.f('ix_received_events_id'), table_name='received_events')
    op.drop_index(op.f('ix_received_events_esp_id'), table_name='received_events')
    op.drop_index(op.f('ix_received_events_data_on'), table_name='received_events')
    op.drop_index(op.f('ix_received_events_ativo'), table_name='received_events')
    op.drop_index(op.f('ix_received_events_action'), table_name='received_events')
    op.drop_table('received_events')
    op.drop_index(op.f('ix_quartos_id'), table_name='quartos')
    op.drop_table('quartos')
    op.drop_index(op.f('ix_global_settings_key'), table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
